import Head from "next/head";
import React from "react";
import CustomTable from "../components/CustomTable";
import styles from "../styles/Home.module.css";

export default function Home({ coupons }: any) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CustomTable data={coupons} />
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const coupons = await fetch(
    "https://storage.googleapis.com/coding_challenge_assets/data.json"
  )
    .then((res) => res.json())
    .then((res) => res.data.coupon);

  return {
    props: { coupons },
  };
};
