import Head from "next/head";
import React from "react";
import CustomTable from "../components/CustomTable";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [state, setState] = React.useState([]);

  React.useEffect(() => {
    fetch("/api/data.json")
      .then((res) => res.json())
      .then((res) => {
        setState(res.data.coupon);
      });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CustomTable data={state} />
      </main>
    </div>
  );
}
